apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-demo-process
  namespace: microservices-demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: microservices-demo-process
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microservices-demo-process
    spec:
      containers:
      - name: microservices-demo-process
        image: registry.nebula-west.home-k8s.lab/k8s/microservices-demo-process
        ports:
        - containerPort: 8000
        env:
          # Postgresql config
          - name: DB_HOST
            value: "postgresql"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: "postgres"
          # - name: DB_PASS
          #   value: "admin123xyz"
          - name: DB
            value: "postgres"
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: postgres-password